"use client";

import { useState } from 'react';
import { Button, Input, Label, Table, TableBody, TableCell, TableHead, TableHeader, TableRow, Badge } from '@trusanity/ui';
import * as DialogPrimitive from '@radix-ui/react-dialog';
import { createFeatureFlag, toggleFeatureFlag, updateFlagRollout } from '@/actions/flags';
// Lucide icons for UI enhancements
import { Plus, Power, Settings2, Trash } from 'lucide-react';

interface Flag {
    id: string;
    key: string;
    description: string | null;
    isActive: boolean;
    rolloutPercentage: number;
}

export default function FlagManagerClient({ projectId, initialFlags }: { projectId: string; initialFlags: Flag[] }) {
    const [flags, setFlags] = useState<Flag[]>(initialFlags);
    const [isDialogOpen, setIsDialogOpen] = useState(false);

    // New flag state
    const [newKey, setNewKey] = useState('');
    const [newDesc, setNewDesc] = useState('');
    const [newRollout, setNewRollout] = useState(100);

    const handleCreate = async () => {
        try {
            await createFeatureFlag(projectId, newKey.trim(), newDesc.trim(), newRollout);
            // In a real app we'd fetch the actual ID generated by Postgres, for optimistic UI we reload or mock
            window.location.reload();
        } catch (e) {
            alert('Failed to create flag. Ensure the key is unique.');
        }
    };

    const handleToggle = async (id: string, currentStatus: boolean) => {
        try {
            await toggleFeatureFlag(id, projectId, !currentStatus);
            setFlags(flags.map(f => f.id === id ? { ...f, isActive: !currentStatus } : f));
        } catch (e) {
            console.error("Toggle Failed");
        }
    };

    return (
        <div className="space-y-4">
            <div className="flex justify-between items-center bg-gray-50/50 p-4 rounded-lg border border-dashed">
                <div className="text-sm text-gray-500">
                    Use <code className="bg-gray-200 px-1 py-0.5 rounded text-black text-xs">netra.evaluateFlag('key')</code> in your code to resolve these states.
                </div>
                <Button onClick={() => setIsDialogOpen(true)} className="gap-2">
                    <Plus className="w-4 h-4" /> Create Flag
                </Button>
            </div>

            <div className="border rounded-md">
                <Table>
                    <TableHeader className="bg-gray-50/50">
                        <TableRow>
                            <TableHead>Flag Key</TableHead>
                            <TableHead>Status</TableHead>
                            <TableHead>Rollout %</TableHead>
                            <TableHead>Eval Code</TableHead>
                            <TableHead className="text-right">Manage</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {flags.length === 0 ? (
                            <TableRow>
                                <TableCell colSpan={5} className="text-center h-24 text-muted-foreground">
                                    No feature flags created yet.
                                </TableCell>
                            </TableRow>
                        ) : flags.map((flag) => (
                            <TableRow key={flag.id}>
                                <TableCell className="font-medium">
                                    <div className="flex flex-col">
                                        <span>{flag.key}</span>
                                        {flag.description && <span className="text-xs text-muted-foreground font-normal">{flag.description}</span>}
                                    </div>
                                </TableCell>
                                <TableCell>
                                    <Badge className={flag.isActive ? 'bg-green-500 hover:bg-green-600' : 'bg-gray-300 text-gray-700 hover:bg-gray-400'}>
                                        {flag.isActive ? 'Enabled' : 'Disabled'}
                                    </Badge>
                                </TableCell>
                                <TableCell>
                                    <div className="flex items-center gap-2">
                                        <div className="w-16 h-2 bg-gray-200 rounded-full overflow-hidden">
                                            <div
                                                className={`h-full ${flag.isActive ? 'bg-blue-500' : 'bg-gray-400'}`}
                                                style={{ width: flag.rolloutPercentage + '%' }}
                                            />
                                        </div>
                                        <span className="text-xs font-mono">{flag.rolloutPercentage}%</span>
                                    </div>
                                </TableCell>
                                <TableCell>
                                    <code className="text-xs bg-gray-100 px-1 py-0.5 rounded text-gray-600 border">
                                        evaluate(&apos;{flag.key}&apos;)
                                    </code>
                                </TableCell>
                                <TableCell className="text-right space-x-2">
                                    {/* Action Buttons */}
                                    <Button
                                        variant="outline"
                                        size="sm"
                                        onClick={() => handleToggle(flag.id, flag.isActive)}
                                        className={flag.isActive ? "text-red-500 hover:text-red-600" : "text-green-600 hover:text-green-700"}
                                    >
                                        <Power className="w-4 h-4 mr-1" />
                                        {flag.isActive ? 'Disable' : 'Enable'}
                                    </Button>
                                    <Button variant="ghost" size="icon" className="h-8 w-8 text-gray-500 hover:text-red-500 hover:bg-red-50 rounded-full">
                                        <Trash className="w-4 h-4" />
                                    </Button>
                                </TableCell>
                            </TableRow>
                        ))}
                    </TableBody>
                </Table>
            </div>

            {/* Creation Dialog Primitive Wrapper */}
            <DialogPrimitive.Root open={isDialogOpen} onOpenChange={setIsDialogOpen}>
                <DialogPrimitive.Portal>
                    <DialogPrimitive.Overlay className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 pointer-events-auto transition-opacity" />
                    <DialogPrimitive.Content className="fixed left-1/2 top-1/2 z-50 w-full max-w-md -translate-x-1/2 -translate-y-1/2 bg-white rounded-xl shadow-lg border p-6">
                        <DialogPrimitive.Title className="text-xl font-bold mb-4 tracking-tight">Create Feature Flag</DialogPrimitive.Title>

                        <div className="space-y-4">
                            <div className="space-y-2">
                                <Label htmlFor="key" className="text-xs font-semibold uppercase text-gray-500">Flag Key</Label>
                                <Input
                                    id="key"
                                    placeholder="e.g. new-checkout-flow"
                                    value={newKey}
                                    onChange={(e) => setNewKey(e.target.value.toLowerCase().replace(/\\s+/g, '-'))}
                                />
                            </div>

                            <div className="space-y-2">
                                <Label htmlFor="desc" className="text-xs font-semibold uppercase text-gray-500">Description (Optional)</Label>
                                <Input
                                    id="desc"
                                    placeholder="What does this flag control?"
                                    value={newDesc}
                                    onChange={(e) => setNewDesc(e.target.value)}
                                />
                            </div>

                            <div className="space-y-2 pt-2">
                                <div className="flex justify-between">
                                    <Label htmlFor="rollout" className="text-xs font-semibold uppercase text-gray-500">Initial Rollout %</Label>
                                    <span className="text-xs font-mono font-medium">{newRollout}%</span>
                                </div>
                                <input
                                    type="range"
                                    id="rollout"
                                    min="0" max="100" step="1"
                                    className="w-full accent-blue-600"
                                    value={newRollout}
                                    onChange={(e) => setNewRollout(Number(e.target.value))}
                                />
                            </div>
                        </div>

                        <div className="flex justify-end space-x-2 mt-8 pt-4 border-t">
                            <Button className="bg-gray-100 hover:bg-gray-200 text-gray-800" onClick={() => setIsDialogOpen(false)}>
                                Cancel
                            </Button>
                            <Button onClick={handleCreate} disabled={!newKey || newKey.length < 3}>
                                Create Flag
                            </Button>
                        </div>
                    </DialogPrimitive.Content>
                </DialogPrimitive.Portal>
            </DialogPrimitive.Root>
        </div>
    );
}
